#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/dev/block/179:0 ; do
	echo "Waiting for internal mmc..."
	busybox sleep 1
done

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

# use blkid to detect fs type for /system
system_fs=$(busybox blkid '/dev/lvpool/system' | busybox awk -F 'TYPE=' '{print $2}' | busybox sed -e 's/"//g')
busybox echo "detected fs type $system_fs for /system" >>boot.txt
# unlikely but adding check anyway
# we don;t have acess to /proc/filesystems so we hardcode ext4 and f2fs
if busybox test  "$system_fs" = 'ext4' || busybox test "$system_fs" = 'f2fs'; then
busybox mount -t "$system_fs" /dev/lvpool/system /system
else
# let mount decide the fs type
busybox echo "auto detecting fail, relying on mount" >>boot.txt
busybox mount /dev/lvpool/system /system
fi;
busybox mount -t ext4 /dev/block/mmcblk0p3 /cache

image=/stage1/ramdisk.cpio

if busybox test -e /cache/.startrecovery || \
   busybox grep -q bootmode=2 /proc/cmdline || \
   busybox grep -q bootmode=9 /proc/cmdline; then
	# recovery boot
	busybox echo 'RECOVERY BOOT' >>boot.txt
	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.cpio
	busybox echo "loading ramdisk-recovery.cpio" >>boot.txt

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

elif ! busybox test -e /system/build.prop ; then

	# emergency boot
	busybox echo "EMERGENCY BOOT" >>boot.txt
	busybox umount /cache
	make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/mmcblk0p3
	busybox mount -t ext4 /dev/block/mmcblk0p3 /cache

	if ! busybox test -e /cache/recovery ; then
		busybox mkdir /cache/recovery
	fi

	busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard
	busybox sleep 1

	if busybox test -e /sdcard/omni.cfg ; then
		busybox echo "installing: `busybox cat /sdcard/omni.cfg`" >>boot.txt
		busybox echo "creating recovery command" >>boot.txt
		busybox touch /cache/recovery/command
		busybox echo "--update_package=`busybox cat /sdcard/omni.cfg`" > /cache/recovery/command
	else
		busybox echo "omni.cfg not found" >>boot.txt
	fi

	busybox echo "loading ramdisk-recovery.cpio" >>boot.txt
	image=/stage1/ramdisk-recovery.cpio

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

	# umount sdcard
	busybox umount /sdcard

else
	# android boot
	busybox echo "ANDROID BOOT" >>boot.txt
	busybox echo "loading ramdisk.cpio" >>boot.txt
fi

busybox umount /cache
busybox umount /system
busybox rmdir /sdcard

busybox cpio -ui < $image

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -rf /stage1 /dev/*
export PATH="${_PATH}"
exec /init
